name: lunchmoney
description: LunchMoney API wrapper written in Dart
version: 1.0.0
repository: https://github.com/V3ntus/lunchmoney_dart

environment:
  sdk: ^3.3.0

dependencies:
  dio: ^5.4.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
