name: lunchmoney
description: LunchMoney API wrapper written in Dart
version: 1.0.0-alpha
repository: https://github.com/V3ntus/lunchmoney_dart

environment:
  sdk: ^3.3.0

dependencies:
  dio: ^5.4.1
  intl: ^0.19.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
